FROM ghcr.io/crytic/echidna/echidna:v2.0.4

RUN apt-get update && apt-get install -y python3-pip && python3 -m pip install --upgrade pip && python3 -m pip install --root-user-action=ignore optik-tools==0.0.2
