pragma solidity ^0.8.19;
/// automatically generated by Daedaluzz
contract Maze {
  event AssertionFailed(string message);
  uint64 private x;
  uint64 private y;
  mapping (uint64 => bool) public found;
  function moveNorth(uint64 p0, uint64 p1, uint64 p2, uint64 p3, uint64 p4, uint64 p5, uint64 p6, uint64 p7) payable external returns (int64) {
    uint64 ny = y + 1;
    require(ny < 7);
    int64 r = step(x, ny, p0, p1, p2, p3, p4, p5, p6, p7);
    if (0 <= r) { y = ny; }
    return r;
  }
  function moveSouth(uint64 p0, uint64 p1, uint64 p2, uint64 p3, uint64 p4, uint64 p5, uint64 p6, uint64 p7) payable external returns (int64) {
    require(0 < y);
    uint64 ny = y - 1;
    int64 r = step(x, ny, p0, p1, p2, p3, p4, p5, p6, p7);
    if (0 <= r) { y = ny; }
    return r;
  }
  function moveEast(uint64 p0, uint64 p1, uint64 p2, uint64 p3, uint64 p4, uint64 p5, uint64 p6, uint64 p7) payable external returns (int64) {
    uint64 nx = x + 1;
    require(nx < 7);
    int64 r = step(nx, y, p0, p1, p2, p3, p4, p5, p6, p7);
    if (0 <= r) { x = nx; }
    return r;
  }
  function moveWest(uint64 p0, uint64 p1, uint64 p2, uint64 p3, uint64 p4, uint64 p5, uint64 p6, uint64 p7) payable external returns (int64) {
    require(0 < x);
    uint64 nx = x - 1;
    int64 r = step(nx, y, p0, p1, p2, p3, p4, p5, p6, p7);
    if (0 <= r) { x = nx; }
    return r;
  }
  function step(uint64 x, uint64 y, uint64 p0, uint64 p1, uint64 p2, uint64 p3, uint64 p4, uint64 p5, uint64 p6, uint64 p7) internal returns (int64) {
    unchecked {
      if (x == 0 && y == 0) {
        // start
        return 0;
      }
      if (x == 0 && y == 1) {
        if (p1 != uint64(26)) {
          if (p3 < uint64(27)) {
            if (p3 > uint64(uint64(8) + p5)) {
              if (p6 <= uint64(p2 * p6)) {
                if (p6 == uint64(p7 + p1)) {
                  found[1] = true; return -1;  // bug
                }
              }
            }
          }
        }
        return 1;
      }
      if (x == 0 && y == 2) {
        if (p5 == uint64(p6 + p0)) {
          if (p2 <= p6) {
            if (p4 <= uint64(uint64(33) * p5)) {
              if (p1 <= uint64(p0 * p5)) {
                if (p5 != uint64(21)) {
                  if (p1 > uint64(13)) {
                    if (p1 < uint64(uint64(50) * p1)) {
                      if (p6 >= uint64(uint64(6) * p0)) {
                        if (p5 != uint64(uint64(64) * p7)) {
                          if (p3 > uint64(p3 * p7)) {
                            found[2] = true; return -1;  // bug
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 2;
      }
      if (x == 0 && y == 3) {
        if (p2 <= uint64(p4 + p5)) {
          if (p0 <= uint64(uint64(38) * p7)) {
            found[3] = true; return -1;  // bug
          }
        }
        return 3;
      }
      if (x == 0 && y == 4) {
        require(false);  // wall
        return 4;
      }
      if (x == 0 && y == 5) {
        require(false);  // wall
        return 5;
      }
      if (x == 0 && y == 6) {
        if (p0 == uint64(48)) {
          if (p5 > uint64(p4 * p7)) {
            found[6] = true; return -1;  // bug
          }
        }
        return 6;
      }
      if (x == 1 && y == 0) {
        if (p1 < uint64(p4 + p3)) {
          if (p1 > uint64(uint64(27) + p1)) {
            if (p6 < uint64(52)) {
              if (p4 >= uint64(uint64(56) + p7)) {
                if (p5 > uint64(6)) {
                  if (p1 < uint64(p7 * p0)) {
                    if (p5 >= uint64(uint64(58) + p7)) {
                      found[7] = true; return -1;  // bug
                    }
                  }
                }
              }
            }
          }
        }
        return 7;
      }
      if (x == 1 && y == 1) {
        if (p4 <= p7) {
          if (p5 != uint64(uint64(13) * p7)) {
            found[8] = true; return -1;  // bug
          }
        }
        return 8;
      }
      if (x == 1 && y == 2) {
        if (p6 < uint64(uint64(57) + p1)) {
          if (p6 > uint64(47)) {
            if (p1 <= uint64(uint64(58) * p1)) {
              if (p2 <= uint64(uint64(33) + p3)) {
                if (p3 >= p3) {
                  if (p4 != uint64(uint64(26) + p7)) {
                    if (p2 > uint64(uint64(56) * p2)) {
                      if (p0 != uint64(p2 * p3)) {
                        if (p1 <= uint64(p0 + p1)) {
                          found[9] = true; return -1;  // bug
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 9;
      }
      if (x == 1 && y == 3) {
        if (p3 >= uint64(p3 + p1)) {
          if (p7 != uint64(uint64(40) + p6)) {
            if (p0 == p4) {
              if (p6 > uint64(uint64(29) + p3)) {
                if (p6 >= uint64(uint64(55) + p3)) {
                  if (p0 < p5) {
                    if (p2 <= uint64(p6 * p6)) {
                      if (p7 <= uint64(p4 + p6)) {
                        if (p2 >= uint64(24)) {
                          if (p5 > uint64(p7 * p3)) {
                            if (p3 <= uint64(p6 * p2)) {
                              found[10] = true; return -1;  // bug
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 10;
      }
      if (x == 1 && y == 4) {
        if (p5 != uint64(59)) {
          if (p7 != p4) {
            if (p4 != p5) {
              if (p1 == uint64(uint64(42) + p4)) {
                if (p0 >= p2) {
                  if (p7 > uint64(uint64(34) * p6)) {
                    if (p2 > uint64(2)) {
                      if (p7 > uint64(p4 + p5)) {
                        found[11] = true; return -1;  // bug
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 11;
      }
      if (x == 1 && y == 5) {
        if (p7 == uint64(8)) {
          if (p3 >= p1) {
            if (p4 > uint64(p0 + p6)) {
              found[12] = true; return -1;  // bug
            }
          }
        }
        return 12;
      }
      if (x == 1 && y == 6) {
        if (p2 == p4) {
          if (p3 > uint64(uint64(22) * p7)) {
            if (p4 > uint64(61)) {
              if (p1 == uint64(uint64(59) + p5)) {
                if (p1 <= uint64(p4 + p7)) {
                  if (p0 < uint64(p6 * p4)) {
                    if (p4 >= uint64(uint64(3) * p0)) {
                      if (p4 != uint64(uint64(48) + p3)) {
                        if (p0 != uint64(uint64(52) + p6)) {
                          if (p2 == p7) {
                            if (p5 >= p1) {
                              if (p3 > uint64(uint64(45) * p5)) {
                                if (p5 <= uint64(p1 * p0)) {
                                  found[13] = true; return -1;  // bug
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 13;
      }
      if (x == 2 && y == 0) {
        if (p7 == uint64(uint64(8) * p6)) {
          if (p5 >= p1) {
            if (p6 > uint64(50)) {
              if (p7 != uint64(51)) {
                if (p2 >= uint64(p5 * p2)) {
                  if (p2 < uint64(p6 + p7)) {
                    if (p7 > uint64(p7 * p3)) {
                      if (p5 == uint64(p3 + p3)) {
                        if (p4 == uint64(uint64(40) + p6)) {
                          if (p1 < uint64(p4 + p6)) {
                            if (p3 <= uint64(uint64(21) + p4)) {
                              if (p1 != uint64(p3 + p1)) {
                                if (p4 > p4) {
                                  if (p1 == uint64(uint64(28) * p3)) {
                                    if (p3 > p6) {
                                      found[14] = true; return -1;  // bug
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 14;
      }
      if (x == 2 && y == 1) {
        if (p6 == uint64(p0 + p4)) {
          if (p6 <= p0) {
            if (p1 < uint64(uint64(46) * p4)) {
              if (p4 == uint64(22)) {
                if (p6 == uint64(uint64(64) * p3)) {
                  if (p6 == uint64(uint64(10) * p4)) {
                    if (p6 > uint64(uint64(6) * p4)) {
                      if (p3 >= uint64(p3 + p5)) {
                        if (p1 != uint64(uint64(56) + p5)) {
                          if (p2 <= uint64(p0 + p4)) {
                            if (p5 < uint64(p5 * p2)) {
                              if (p4 != uint64(p5 * p3)) {
                                if (p1 >= uint64(5)) {
                                  if (p4 == uint64(61)) {
                                    if (p0 <= uint64(42)) {
                                      found[15] = true; return -1;  // bug
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 15;
      }
      if (x == 2 && y == 2) {
        if (p6 <= uint64(p3 * p4)) {
          if (p6 < uint64(uint64(62) + p2)) {
            if (p4 >= p0) {
              if (p3 <= uint64(uint64(56) + p7)) {
                if (p0 >= uint64(uint64(32) + p2)) {
                  if (p1 >= uint64(p0 * p2)) {
                    if (p0 != uint64(uint64(43) * p5)) {
                      if (p5 == uint64(uint64(63) * p5)) {
                        found[16] = true; return -1;  // bug
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 16;
      }
      if (x == 2 && y == 3) {
        if (p6 != p7) {
          if (p4 <= uint64(p2 + p4)) {
            if (p7 != uint64(9)) {
              if (p5 <= uint64(33)) {
                if (p3 != p3) {
                  if (p7 >= uint64(uint64(32) + p4)) {
                    if (p7 >= uint64(uint64(59) * p1)) {
                      if (p6 > uint64(uint64(27) + p1)) {
                        if (p6 > p2) {
                          found[17] = true; return -1;  // bug
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 17;
      }
      if (x == 2 && y == 4) {
        if (p5 > p1) {
          if (p0 == uint64(p4 * p7)) {
            if (p6 < uint64(p0 + p2)) {
              if (p3 >= uint64(uint64(57) * p1)) {
                if (p1 >= uint64(p6 * p1)) {
                  if (p7 <= uint64(64)) {
                    if (p2 < uint64(p6 + p0)) {
                      if (p0 < p5) {
                        if (p1 > uint64(p5 + p4)) {
                          if (p2 > p0) {
                            if (p0 >= uint64(p4 * p3)) {
                              if (p1 < uint64(p1 + p5)) {
                                if (p1 < uint64(uint64(48) * p7)) {
                                  if (p4 == uint64(uint64(34) * p5)) {
                                    found[18] = true; return -1;  // bug
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 18;
      }
      if (x == 2 && y == 5) {
        require(false);  // wall
        return 19;
      }
      if (x == 2 && y == 6) {
        if (p7 <= uint64(22)) {
          if (p7 == uint64(p0 * p4)) {
            if (p4 <= uint64(8)) {
              if (p6 <= p5) {
                if (p1 > uint64(p5 * p7)) {
                  if (p7 < uint64(p7 * p5)) {
                    if (p7 <= uint64(uint64(3) * p5)) {
                      if (p3 <= p5) {
                        if (p6 >= uint64(uint64(13) * p5)) {
                          found[20] = true; return -1;  // bug
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 20;
      }
      if (x == 3 && y == 0) {
        require(false);  // wall
        return 21;
      }
      if (x == 3 && y == 1) {
        if (p6 != uint64(p6 * p1)) {
          if (p2 < uint64(uint64(36) * p3)) {
            if (p6 > uint64(p4 + p4)) {
              if (p3 >= p0) {
                if (p0 == uint64(p4 + p1)) {
                  if (p2 <= uint64(uint64(31) * p2)) {
                    if (p7 < uint64(uint64(55) + p2)) {
                      if (p7 != p7) {
                        if (p6 < p6) {
                          if (p1 < uint64(uint64(13) * p2)) {
                            if (p3 > p6) {
                              if (p5 != uint64(p3 + p1)) {
                                if (p4 != uint64(uint64(51) + p6)) {
                                  if (p1 != uint64(p3 * p3)) {
                                    if (p2 < p3) {
                                      found[22] = true; return -1;  // bug
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 22;
      }
      if (x == 3 && y == 2) {
        if (p6 > uint64(p7 * p0)) {
          if (p2 <= uint64(p6 + p4)) {
            if (p2 == p7) {
              if (p0 > p1) {
                if (p3 > uint64(uint64(28) + p0)) {
                  if (p4 <= uint64(uint64(36) * p0)) {
                    if (p7 > uint64(p0 + p4)) {
                      if (p5 >= uint64(p0 + p3)) {
                        found[23] = true; return -1;  // bug
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 23;
      }
      if (x == 3 && y == 3) {
        if (p4 > uint64(60)) {
          if (p7 >= uint64(uint64(18) * p3)) {
            if (p5 >= uint64(uint64(49) * p4)) {
              if (p3 <= p0) {
                if (p2 != uint64(p2 + p5)) {
                  if (p0 <= uint64(uint64(11) * p3)) {
                    if (p2 >= uint64(uint64(18) * p6)) {
                      if (p3 != p5) {
                        if (p1 <= uint64(uint64(42) + p7)) {
                          if (p5 == uint64(uint64(21) + p5)) {
                            if (p5 >= uint64(uint64(49) + p4)) {
                              found[24] = true; return -1;  // bug
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 24;
      }
      if (x == 3 && y == 4) {
        if (p5 > uint64(p0 * p4)) {
          if (p3 > p4) {
            if (p0 != uint64(p5 * p1)) {
              if (p3 < uint64(7)) {
                if (p7 != uint64(uint64(11) + p1)) {
                  if (p7 != p3) {
                    found[25] = true; return -1;  // bug
                  }
                }
              }
            }
          }
        }
        return 25;
      }
      if (x == 3 && y == 5) {
        if (p5 < uint64(37)) {
          if (p3 <= uint64(p5 * p7)) {
            if (p2 == uint64(36)) {
              if (p6 >= uint64(6)) {
                if (p6 != uint64(p2 * p5)) {
                  if (p5 > p4) {
                    if (p1 < uint64(18)) {
                      if (p4 > p6) {
                        if (p5 <= uint64(p7 + p0)) {
                          if (p5 != p1) {
                            if (p0 != uint64(uint64(42) + p1)) {
                              if (p0 != uint64(p5 + p6)) {
                                if (p6 <= uint64(p3 * p5)) {
                                  if (p6 != uint64(uint64(12) * p6)) {
                                    if (p2 > uint64(p4 * p4)) {
                                      if (p6 < uint64(uint64(23) * p6)) {
                                        found[26] = true; return -1;  // bug
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 26;
      }
      if (x == 3 && y == 6) {
        if (p6 == uint64(uint64(12) + p3)) {
          if (p1 >= uint64(uint64(52) * p6)) {
            if (p1 < uint64(uint64(20) + p0)) {
              if (p6 > uint64(5)) {
                if (p3 <= uint64(25)) {
                  if (p4 >= uint64(p2 * p2)) {
                    if (p4 != uint64(uint64(16) * p3)) {
                      if (p6 > uint64(uint64(27) * p7)) {
                        if (p3 > uint64(uint64(47) * p1)) {
                          if (p2 != uint64(uint64(23) * p5)) {
                            if (p5 > uint64(uint64(50) * p0)) {
                              if (p1 < uint64(uint64(52) * p6)) {
                                if (p0 != uint64(p1 * p6)) {
                                  if (p4 == uint64(19)) {
                                    found[27] = true; return -1;  // bug
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 27;
      }
      if (x == 4 && y == 0) {
        require(false);  // wall
        return 28;
      }
      if (x == 4 && y == 1) {
        if (p2 <= uint64(uint64(52) + p7)) {
          if (p6 >= uint64(p2 + p5)) {
            if (p4 <= p0) {
              if (p7 > uint64(p2 + p7)) {
                if (p4 <= uint64(52)) {
                  if (p3 >= uint64(uint64(33) * p0)) {
                    if (p2 >= uint64(p4 * p3)) {
                      if (p2 < p5) {
                        if (p1 == uint64(p2 * p6)) {
                          if (p5 != p7) {
                            found[29] = true; return -1;  // bug
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 29;
      }
      if (x == 4 && y == 2) {
        if (p1 <= uint64(p0 + p5)) {
          if (p0 > uint64(uint64(58) * p2)) {
            if (p5 < p2) {
              if (p6 > uint64(uint64(42) * p4)) {
                if (p3 == uint64(uint64(54) * p0)) {
                  if (p1 >= uint64(p1 + p1)) {
                    if (p5 >= p6) {
                      if (p6 != uint64(uint64(39) + p1)) {
                        if (p4 == uint64(uint64(30) + p2)) {
                          found[30] = true; return -1;  // bug
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 30;
      }
      if (x == 4 && y == 3) {
        if (p2 < p4) {
          if (p2 >= uint64(p0 * p2)) {
            if (p2 >= p0) {
              if (p6 == uint64(19)) {
                if (p5 < uint64(uint64(41) + p7)) {
                  if (p3 < uint64(uint64(23) + p7)) {
                    if (p6 == uint64(p4 * p6)) {
                      if (p1 > uint64(uint64(51) + p6)) {
                        if (p4 < uint64(p4 * p4)) {
                          if (p1 >= p0) {
                            if (p1 != uint64(49)) {
                              if (p1 != uint64(uint64(23) * p1)) {
                                if (p7 < p7) {
                                  if (p6 <= uint64(26)) {
                                    if (p6 >= uint64(25)) {
                                      if (p3 > uint64(p5 + p3)) {
                                        found[31] = true; return -1;  // bug
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 31;
      }
      if (x == 4 && y == 4) {
        if (p7 >= uint64(p0 + p5)) {
          if (p5 == uint64(uint64(26) * p0)) {
            if (p7 == uint64(p4 * p0)) {
              if (p0 <= p0) {
                if (p5 > uint64(p2 * p5)) {
                  if (p1 <= uint64(uint64(28) * p4)) {
                    if (p2 > uint64(p4 + p0)) {
                      if (p4 <= uint64(36)) {
                        if (p3 > p0) {
                          if (p6 > uint64(p6 * p7)) {
                            if (p7 >= uint64(p3 + p3)) {
                              if (p4 > p3) {
                                found[32] = true; return -1;  // bug
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 32;
      }
      if (x == 4 && y == 5) {
        if (p4 <= p7) {
          if (p3 != uint64(p6 * p3)) {
            if (p2 == uint64(uint64(32) * p1)) {
              if (p5 > uint64(uint64(25) * p1)) {
                if (p7 < uint64(uint64(45) * p7)) {
                  if (p7 >= uint64(p4 + p3)) {
                    found[33] = true; return -1;  // bug
                  }
                }
              }
            }
          }
        }
        return 33;
      }
      if (x == 4 && y == 6) {
        if (p5 >= uint64(32)) {
          if (p5 <= uint64(26)) {
            if (p0 != uint64(p3 + p3)) {
              if (p6 == uint64(uint64(12) + p4)) {
                if (p2 != p6) {
                  if (p1 < p1) {
                    if (p1 < uint64(59)) {
                      if (p1 != uint64(uint64(63) + p5)) {
                        if (p1 <= uint64(p5 * p2)) {
                          if (p0 <= uint64(5)) {
                            found[34] = true; return -1;  // bug
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 34;
      }
      if (x == 5 && y == 0) {
        if (p4 == p6) {
          if (p7 <= uint64(uint64(40) + p4)) {
            if (p7 < uint64(17)) {
              if (p4 == uint64(uint64(59) * p6)) {
                if (p0 == uint64(uint64(29) + p0)) {
                  if (p6 != uint64(uint64(40) * p7)) {
                    if (p5 != uint64(uint64(34) * p1)) {
                      if (p4 == uint64(5)) {
                        if (p7 >= uint64(11)) {
                          if (p0 == uint64(p6 * p4)) {
                            if (p4 >= p7) {
                              if (p0 <= uint64(uint64(10) + p7)) {
                                if (p5 <= uint64(41)) {
                                  found[35] = true; return -1;  // bug
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 35;
      }
      if (x == 5 && y == 1) {
        if (p0 <= uint64(uint64(19) * p3)) {
          if (p1 >= p2) {
            if (p7 == p7) {
              if (p0 >= uint64(uint64(47) * p0)) {
                if (p3 >= uint64(uint64(27) + p3)) {
                  if (p2 <= uint64(p3 * p0)) {
                    found[36] = true; return -1;  // bug
                  }
                }
              }
            }
          }
        }
        return 36;
      }
      if (x == 5 && y == 2) {
        if (p5 != uint64(28)) {
          if (p1 > uint64(p4 * p6)) {
            if (p1 != uint64(4)) {
              if (p3 < uint64(uint64(34) + p7)) {
                if (p6 == uint64(uint64(21) + p2)) {
                  if (p1 == uint64(p5 * p6)) {
                    if (p7 <= uint64(uint64(8) * p0)) {
                      if (p0 == uint64(p7 + p0)) {
                        if (p6 == uint64(p1 + p2)) {
                          if (p1 == uint64(uint64(6) + p4)) {
                            if (p2 == uint64(uint64(25) + p3)) {
                              if (p4 < uint64(uint64(58) * p3)) {
                                found[37] = true; return -1;  // bug
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 37;
      }
      if (x == 5 && y == 3) {
        if (p3 <= uint64(p1 * p4)) {
          if (p4 != uint64(p5 + p1)) {
            if (p7 > uint64(uint64(40) + p5)) {
              if (p4 == uint64(19)) {
                if (p2 == uint64(p6 + p7)) {
                  if (p0 > uint64(uint64(0) * p3)) {
                    if (p2 >= uint64(uint64(25) + p2)) {
                      if (p4 > p7) {
                        if (p1 < p5) {
                          if (p0 != uint64(uint64(4) * p7)) {
                            if (p4 < uint64(uint64(19) + p0)) {
                              if (p5 < uint64(p0 + p5)) {
                                if (p3 == uint64(uint64(0) + p7)) {
                                  if (p2 <= uint64(uint64(6) + p1)) {
                                    found[38] = true; return -1;  // bug
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 38;
      }
      if (x == 5 && y == 4) {
        if (p6 == uint64(uint64(42) * p0)) {
          if (p0 == uint64(p0 * p2)) {
            if (p3 < uint64(uint64(25) + p3)) {
              if (p4 == uint64(p6 + p5)) {
                if (p6 <= uint64(53)) {
                  if (p3 <= p5) {
                    if (p2 > uint64(uint64(54) + p5)) {
                      if (p0 <= uint64(p5 * p2)) {
                        if (p0 <= p6) {
                          found[39] = true; return -1;  // bug
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 39;
      }
      if (x == 5 && y == 5) {
        if (p1 != uint64(uint64(2) * p5)) {
          if (p0 >= uint64(p4 * p3)) {
            if (p2 <= uint64(uint64(5) + p2)) {
              if (p1 > uint64(uint64(30) + p0)) {
                if (p2 <= uint64(uint64(25) + p0)) {
                  if (p3 < p6) {
                    if (p1 <= uint64(p1 + p1)) {
                      if (p6 > uint64(uint64(0) + p3)) {
                        if (p0 >= uint64(uint64(46) * p4)) {
                          if (p3 >= uint64(uint64(2) * p0)) {
                            found[40] = true; return -1;  // bug
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 40;
      }
      if (x == 5 && y == 6) {
        if (p3 != uint64(uint64(14) * p0)) {
          if (p7 != p4) {
            if (p0 == uint64(63)) {
              found[41] = true; return -1;  // bug
            }
          }
        }
        return 41;
      }
      if (x == 6 && y == 0) {
        if (p0 < uint64(p0 * p1)) {
          if (p5 < p5) {
            if (p6 != p4) {
              if (p3 > p7) {
                if (p5 != p3) {
                  if (p1 >= uint64(54)) {
                    if (p0 < uint64(uint64(30) * p2)) {
                      if (p2 != p0) {
                        if (p7 < uint64(uint64(53) * p0)) {
                          if (p6 >= p2) {
                            if (p4 <= p1) {
                              found[42] = true; return -1;  // bug
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 42;
      }
      if (x == 6 && y == 1) {
        if (p1 <= uint64(p1 + p3)) {
          if (p4 < uint64(uint64(28) + p0)) {
            if (p2 > p7) {
              if (p3 < uint64(uint64(39) + p4)) {
                if (p5 < uint64(p4 * p1)) {
                  if (p2 < uint64(p7 + p6)) {
                    if (p0 < uint64(p4 * p2)) {
                      if (p4 >= uint64(uint64(43) + p4)) {
                        if (p4 <= uint64(p3 + p4)) {
                          if (p2 < uint64(uint64(12) + p7)) {
                            if (p7 > uint64(p1 * p4)) {
                              if (p3 >= p2) {
                                found[43] = true; return -1;  // bug
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 43;
      }
      if (x == 6 && y == 2) {
        if (p0 <= uint64(uint64(14) * p1)) {
          if (p0 < uint64(uint64(9) * p2)) {
            if (p7 > uint64(uint64(42) * p5)) {
              if (p1 > uint64(uint64(9) + p5)) {
                if (p0 <= uint64(28)) {
                  if (p4 > uint64(p0 + p7)) {
                    if (p1 > uint64(uint64(9) + p1)) {
                      if (p5 > uint64(uint64(3) + p0)) {
                        if (p3 < uint64(21)) {
                          if (p1 <= uint64(uint64(52) * p0)) {
                            if (p0 < uint64(p5 + p3)) {
                              if (p2 >= uint64(21)) {
                                found[44] = true; return -1;  // bug
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 44;
      }
      if (x == 6 && y == 3) {
        if (p1 < p7) {
          if (p0 == p6) {
            if (p3 > uint64(p5 * p5)) {
              if (p1 > uint64(uint64(2) + p6)) {
                if (p3 == uint64(uint64(28) + p2)) {
                  if (p7 <= uint64(p6 * p1)) {
                    if (p2 > uint64(uint64(63) * p0)) {
                      if (p4 != uint64(p6 * p0)) {
                        if (p1 == uint64(uint64(33) + p2)) {
                          if (p1 != uint64(39)) {
                            if (p7 == uint64(55)) {
                              if (p7 > uint64(uint64(17) * p2)) {
                                if (p3 >= uint64(2)) {
                                  if (p7 < uint64(p6 * p1)) {
                                    if (p2 <= uint64(13)) {
                                      if (p1 > uint64(uint64(24) * p2)) {
                                        found[45] = true; return -1;  // bug
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        return 45;
      }
      if (x == 6 && y == 4) {
        require(false);  // wall
        return 46;
      }
      if (x == 6 && y == 5) {
        if (p2 <= uint64(28)) {
          if (p1 >= uint64(uint64(36) + p4)) {
            if (p5 == uint64(uint64(31) * p2)) {
              if (p6 <= p5) {
                if (p2 < p4) {
                  if (p7 != uint64(uint64(25) + p5)) {
                    found[47] = true; return -1;  // bug
                  }
                }
              }
            }
          }
        }
        return 47;
      }
      if (x == 6 && y == 6) {
        require(false);  // wall
        return 48;
      }
      return 49;
    }
  }
}
import "forge-std/Test.sol";
contract TestMaze is Test {
  Maze m;
  function setUp() external {
    m = new Maze();
  }
  function invariant_0() external { if (m.found(0)) { fail("0"); } }
  function invariant_1() external { if (m.found(1)) { fail("1"); } }
  function invariant_2() external { if (m.found(2)) { fail("2"); } }
  function invariant_3() external { if (m.found(3)) { fail("3"); } }
  function invariant_4() external { if (m.found(4)) { fail("4"); } }
  function invariant_5() external { if (m.found(5)) { fail("5"); } }
  function invariant_6() external { if (m.found(6)) { fail("6"); } }
  function invariant_7() external { if (m.found(7)) { fail("7"); } }
  function invariant_8() external { if (m.found(8)) { fail("8"); } }
  function invariant_9() external { if (m.found(9)) { fail("9"); } }
  function invariant_10() external { if (m.found(10)) { fail("10"); } }
  function invariant_11() external { if (m.found(11)) { fail("11"); } }
  function invariant_12() external { if (m.found(12)) { fail("12"); } }
  function invariant_13() external { if (m.found(13)) { fail("13"); } }
  function invariant_14() external { if (m.found(14)) { fail("14"); } }
  function invariant_15() external { if (m.found(15)) { fail("15"); } }
  function invariant_16() external { if (m.found(16)) { fail("16"); } }
  function invariant_17() external { if (m.found(17)) { fail("17"); } }
  function invariant_18() external { if (m.found(18)) { fail("18"); } }
  function invariant_19() external { if (m.found(19)) { fail("19"); } }
  function invariant_20() external { if (m.found(20)) { fail("20"); } }
  function invariant_21() external { if (m.found(21)) { fail("21"); } }
  function invariant_22() external { if (m.found(22)) { fail("22"); } }
  function invariant_23() external { if (m.found(23)) { fail("23"); } }
  function invariant_24() external { if (m.found(24)) { fail("24"); } }
  function invariant_25() external { if (m.found(25)) { fail("25"); } }
  function invariant_26() external { if (m.found(26)) { fail("26"); } }
  function invariant_27() external { if (m.found(27)) { fail("27"); } }
  function invariant_28() external { if (m.found(28)) { fail("28"); } }
  function invariant_29() external { if (m.found(29)) { fail("29"); } }
  function invariant_30() external { if (m.found(30)) { fail("30"); } }
  function invariant_31() external { if (m.found(31)) { fail("31"); } }
  function invariant_32() external { if (m.found(32)) { fail("32"); } }
  function invariant_33() external { if (m.found(33)) { fail("33"); } }
  function invariant_34() external { if (m.found(34)) { fail("34"); } }
  function invariant_35() external { if (m.found(35)) { fail("35"); } }
  function invariant_36() external { if (m.found(36)) { fail("36"); } }
  function invariant_37() external { if (m.found(37)) { fail("37"); } }
  function invariant_38() external { if (m.found(38)) { fail("38"); } }
  function invariant_39() external { if (m.found(39)) { fail("39"); } }
  function invariant_40() external { if (m.found(40)) { fail("40"); } }
  function invariant_41() external { if (m.found(41)) { fail("41"); } }
  function invariant_42() external { if (m.found(42)) { fail("42"); } }
  function invariant_43() external { if (m.found(43)) { fail("43"); } }
  function invariant_44() external { if (m.found(44)) { fail("44"); } }
  function invariant_45() external { if (m.found(45)) { fail("45"); } }
  function invariant_46() external { if (m.found(46)) { fail("46"); } }
  function invariant_47() external { if (m.found(47)) { fail("47"); } }
  function invariant_48() external { if (m.found(48)) { fail("48"); } }
}
